title: Python Docs
description: Course materials for Post-AP Computer Science: Python Applications
theme: just-the-docs

url: https://pythondocs.coderina.dev

aux_links:
  "Instructor Site": 
    - "https://coderina.dev"
